package amir.sepehr.seamchat

import io.ktor.http.HttpStatusCode
import io.ktor.server.request.receive
import io.ktor.server.response.respond
import io.ktor.server.routing.*
import io.ktor.server.websocket.DefaultWebSocketServerSession
import io.ktor.server.websocket.sendSerialized
import io.ktor.server.websocket.webSocket
import io.ktor.websocket.*
import java.util.concurrent.ConcurrentHashMap

class ChatRoutes(private val db:Database){
 private val actions=MessageActions();private val sockets=ConcurrentHashMap<String,MutableSet<DefaultWebSocketServerSession>>();private val onlineUsers=ConcurrentHashMap<String,MutableSet<String>>()
 private suspend fun broadcast(id:String,payload:Any,except:DefaultWebSocketServerSession?=null){sockets[id]?.toList()?.forEach{if(it!=except)runCatching{it.sendSerialized(payload)}}}
 fun register(route:Route){
  route.get("/api/v1/users/search"){val a=authFromCall(call,db)?:return@get call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val q=call.request.queryParameters["q"]?.trim().orEmpty();if(q.length<2)return@get call.respond(emptyList<UserDto>());call.respond(db.searchUsers(q,a.user.id))}
  route.get("/api/v1/conversations"){val a=authFromCall(call,db)?:return@get call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));call.respond(db.conversations(a.user.id))}
  route.post("/api/v1/conversations/direct"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));try{call.respond(HttpStatusCode.Created,db.createDirectConversation(a.user.id,call.receive<CreateDirectConversationRequest>().userId))}catch(e:IllegalArgumentException){call.respond(HttpStatusCode.BadRequest,ErrorResponse(e.message?:"Invalid conversation"))}}
  route.post("/api/v1/conversations/{id}/read"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val id=call.parameters["id"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing conversation id"));if(!db.isMember(id,a.user.id))return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Not a conversation member"));db.markRead(id,a.user.id);broadcast(id,RealtimeEvent("read",a.user.id));call.respond(mapOf("ok" to true))}
  route.get("/api/v1/conversations/{id}/messages"){val a=authFromCall(call,db)?:return@get call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val id=call.parameters["id"]?:return@get call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing conversation id"));if(!db.isMember(id,a.user.id))return@get call.respond(HttpStatusCode.Forbidden,ErrorResponse("Not a conversation member"));call.respond(db.messages(id))}
  route.post("/api/v1/conversations/{id}/messages"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val id=call.parameters["id"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing conversation id"));if(!db.isMember(id,a.user.id))return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Not a conversation member"));val r=call.receive<SendMessageRequest>();if(r.body.isBlank()||r.body.length>10000)return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Message must be 1-10000 characters."));val type=r.type.lowercase().takeIf{it in setOf("text","image","video","audio","file")}?:"text";val m=db.insertMessage(id,a.user.id,r.body.trim(),type);broadcast(id,RealtimeEvent("message",a.user.id,messageId=m.id,body=m.body,createdAt=m.createdAt));call.respond(HttpStatusCode.Created,m)}
  route.post("/api/v1/messages/{messageId}/reply"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));val r=call.receive<ReplyMessageRequest>();if(r.body.isBlank()||r.body.length>10000)return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Invalid reply"));val m=actions.reply(mid,a.user.id,r.body,r.type)?:return@post call.respond(HttpStatusCode.NotFound,ErrorResponse("Message not found"));if(!db.isMember(m.conversationId,a.user.id))return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Not a conversation member"));broadcast(m.conversationId,RealtimeEvent("message",a.user.id,messageId=m.id,body=m.body,createdAt=m.createdAt));call.respond(HttpStatusCode.Created,m)}
  route.post("/api/v1/messages/{messageId}/edit"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));val r=call.receive<EditMessageRequest>();if(r.body.isBlank()||r.body.length>10000)return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Invalid message body"));val m=actions.edit(mid,a.user.id,r.body)?:return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Message cannot be edited"));broadcast(m.conversationId,RealtimeEvent("message_edited",a.user.id,messageId=m.id,body=m.body,createdAt=m.editedAt));call.respond(m)}
  route.post("/api/v1/messages/{messageId}/delete"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));if(!actions.delete(mid,a.user.id))return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Message cannot be deleted"));call.respond(mapOf("ok" to true,"messageId" to mid))}
  route.post("/api/v1/messages/{messageId}/forward"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));val r=call.receive<ForwardMessageRequest>();if(!db.isMember(r.conversationId,a.user.id))return@post call.respond(HttpStatusCode.Forbidden,ErrorResponse("Not a conversation member"));val m=actions.forward(mid,a.user.id,r.conversationId)?:return@post call.respond(HttpStatusCode.NotFound,ErrorResponse("Message not found"));broadcast(r.conversationId,RealtimeEvent("message",a.user.id,messageId=m.id,body=m.body,createdAt=m.createdAt));call.respond(HttpStatusCode.Created,m)}
  route.post("/api/v1/messages/{messageId}/reaction"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));val r=call.receive<ReactionRequest>();if(r.reaction.isBlank())return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Reaction is required"));call.respond(mapOf("ok" to true,"added" to actions.react(mid,a.user.id,r.reaction),"reaction" to r.reaction))}
  route.post("/api/v1/messages/{messageId}/reaction/remove"){val a=authFromCall(call,db)?:return@post call.respond(HttpStatusCode.Unauthorized,ErrorResponse("Unauthorized"));val mid=call.parameters["messageId"]?:return@post call.respond(HttpStatusCode.BadRequest,ErrorResponse("Missing message id"));val r=call.receive<ReactionRequest>();call.respond(mapOf("ok" to true,"removed" to actions.unreact(mid,a.user.id,r.reaction),"reaction" to r.reaction))}
  route.webSocket("/api/v1/realtime/{conversationId}"){val a=authFromCall(call,db);val cid=call.parameters["conversationId"];if(a==null||cid==null||!db.isMember(cid,a.user.id)){close(CloseReason(CloseReason.Codes.VIOLATED_POLICY,"Unauthorized"));return@webSocket};val uid=a.user.id;val set=sockets.computeIfAbsent(cid){ConcurrentHashMap.newKeySet()};val users=onlineUsers.computeIfAbsent(cid){ConcurrentHashMap.newKeySet()};set.add(this);users.add(uid);broadcast(cid,RealtimeEvent("presence",uid,online=true),this);sendSerialized(RealtimeEvent("presence_snapshot",uid,onlineUsers=users.toList()));try{for(f in incoming)if(f is Frame.Text){val t=f.readText().trim();when{t=="ping"->send("pong");t.startsWith("{\"type\":\"typing\"")->broadcast(cid,RealtimeEvent("typing",uid,value=t.contains("\"value\":true")),this);t.startsWith("{\"type\":\"read\"")->Regex("\\\"messageId\\\"\\s*:\\s*\\\"([^\\\"]+)\\\"").find(t)?.groupValues?.get(1)?.let{broadcast(cid,RealtimeEvent("read",uid,messageId=it),this)}}}}finally{set.remove(this);users.remove(uid);if(set.isEmpty())sockets.remove(cid,set);if(users.isEmpty())onlineUsers.remove(cid,users);broadcast(cid,RealtimeEvent("presence",uid,online=false),this)}}
 }
}

data class RealtimeEvent(val type:String,val userId:String,val messageId:String?=null,val body:String?=null,val createdAt:Long?=null,val value:Boolean?=null,val online:Boolean?=null,val onlineUsers:List<String>?=null)
