const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const state = { user:null, activeUser:null, socket:null, reconnectTimer:null, reconnectAttempt:0, intentionalClose:false, chats:[], messages:new Map(), onlineUsers:new Set(), typingUsers:new Set(), loadingHistory:new Set(), searchTimer:null, users:[] };
const tokenKey='seam_chat_token';
const apiBase=(window.SEAM_API_BASE||location.origin).replace(/\/$/,'');

function wsUrl(){const url=new URL(apiBase+'/ws');url.protocol=url.protocol==='https:'?'wss:':'ws:';url.searchParams.set('token',localStorage.getItem(tokenKey)||'');return url.toString()}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2800)}
function initials(name){return(name||'?').slice(0,1).toUpperCase()}
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function authHeaders(){const token=localStorage.getItem(tokenKey);return token?{Authorization:`Bearer ${token}`}:{}}
async function api(path,options={}){const response=await fetch(`${apiBase}${path}`,{...options,headers:{Accept:'application/json','Content-Type':'application/json',...authHeaders(),...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||`خطا (${response.status})`);error.status=response.status;throw error}return data}
function setConnectionStatus(text){$('#connectionStatus').textContent=text}
function formatTime(value){return value?new Date(value).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}):''}
function formatDate(value){return value?new Date(value).toLocaleDateString('fa-IR',{day:'numeric',month:'long'}):''}
function messageStatus(m){if(m.sender!==state.user?.username)return '';if(m.readAt)return 'خوانده شد';if(m.deliveredAt)return 'تحویل شد';return 'ارسال شد'}

function renderChats(filter=''){
  const q=filter.trim().toLowerCase();const chats=state.chats.filter(c=>c.username.toLowerCase().includes(q));const list=$('#chatList');
  const chatHtml=chats.map(c=>`<button class="chat-row ${state.activeUser===c.username?'selected':''}" data-name="${escapeHtml(c.username)}"><span class="avatar">${escapeHtml(initials(c.username))}</span><span class="chat-copy"><strong>${escapeHtml(c.username)}</strong><small>${escapeHtml(c.lastMessage||'گفتگو را شروع کنید')}</small></span><span class="chat-meta"><time>${formatTime(c.lastMessageAt)}</time>${c.unreadCount?`<b>${c.unreadCount}</b>`:''}</span></button>`).join('');
  const usersHtml=state.users.filter(u=>u.username.toLowerCase().includes(q)).map(u=>`<button class="chat-row user-result" data-user="${escapeHtml(u.username)}"><span class="avatar avatar-green">${escapeHtml(initials(u.username))}</span><span class="chat-copy"><strong>${escapeHtml(u.username)}</strong><small>شروع گفتگوی جدید</small></span><span class="chat-meta"><small>کاربر</small></span></button>`).join('');
  if(q && usersHtml)list.innerHTML=`<div class="result-title">کاربران</div>${usersHtml}<div class="result-title">گفتگوها</div>${chatHtml||'<div class="empty-state">گفتگویی با این عبارت پیدا نشد.</div>'}`;
  else list.innerHTML=chatHtml|| (q?'<div class="empty-state">کاربری با این نام پیدا نشد.</div>':'<div class="empty-state">هنوز گفتگویی ندارید.<br>از «＋» برای شروع استفاده کنید.</div>');
  list.querySelectorAll('[data-name]').forEach(row=>row.addEventListener('click',()=>openChat(row.dataset.name)));
  list.querySelectorAll('[data-user]').forEach(row=>row.addEventListener('click',()=>openChat(row.dataset.user)));
}

function renderMessages(){
  const area=$('#messageArea');const messages=state.messages.get(state.activeUser)||[];
  $('#loadOlder').hidden=!messages.length;
  if(!messages.length){area.innerHTML='<div class="empty-conversation"><div class="empty-icon">✦</div><strong>هنوز پیامی نیست</strong><span>اولین پیام را شما بفرستید.</span></div>';return}
  let lastDate='';let html='';
  for(const m of messages){const date=formatDate(m.createdAt);if(date!==lastDate){html+=`<div class="date-pill">${escapeHtml(date)}</div>`;lastDate=date}const mine=m.sender===state.user.username;html+=`<article class="message ${mine?'sent':'received'}"><div>${!mine?`<span class="bubble-avatar">${escapeHtml(initials(m.sender))}</span>`:''}<p>${escapeHtml(m.body)}</p><time>${formatTime(m.createdAt)}${mine?` · ${escapeHtml(messageStatus(m))}`:''}</time></div></article>`}
  area.innerHTML=html;area.scrollTop=area.scrollHeight;
}
function addMessage(message){const other=message.sender===state.user.username?message.recipient:message.sender;const list=state.messages.get(other)||[];const idx=list.findIndex(m=>String(m.id)===String(message.id));if(idx<0)list.push(message);else list[idx]={...list[idx],...message};list.sort((a,b)=>Number(a.id)-Number(b.id));state.messages.set(other,list);let chat=state.chats.find(c=>c.username===other);if(!chat){chat={username:other,lastMessage:message.body,lastMessageAt:message.createdAt,unreadCount:0};state.chats.push(chat)}chat.lastMessage=message.body;chat.lastMessageAt=message.createdAt;if(message.sender!==state.user.username&&state.activeUser!==other)chat.unreadCount=(chat.unreadCount||0)+1;state.chats.sort((a,b)=>new Date(b.lastMessageAt||0)-new Date(a.lastMessageAt||0));renderChats($('#searchInput').value);if(state.activeUser===other){renderMessages();if(message.sender!==state.user.username)markRead(other).catch(()=>{})}}
function updateMessageStatus(id,patch){for(const [username,list] of state.messages){const m=list.find(x=>String(x.id)===String(id));if(m){Object.assign(m,patch);if(username===state.activeUser)renderMessages();return}}}

async function loadMe(){const data=await api('/api/me');state.user=data.user;$('#profileBtn').textContent=initials(state.user.username)}
async function loadChats(){const data=await api('/api/chats');state.chats=data.chats||[];renderChats($('#searchInput').value)}
async function loadPresence(){try{const data=await api('/api/presence');state.onlineUsers=new Set(data.users||[]);updateActiveStatus()}catch{}}
async function searchUsers(query){if(!query.trim()){state.users=[];renderChats('');return}clearTimeout(state.searchTimer);state.searchTimer=setTimeout(async()=>{try{const data=await api(`/api/users/search?q=${encodeURIComponent(query.trim())}`);state.users=data.users||[];renderChats(query)}catch{state.users=[];renderChats(query)}},180)}
async function openChat(username){if(!username||username===state.user.username)return toast('نمی‌توانید با خودتان گفتگو کنید.');state.activeUser=username;$('#activeName').textContent=username;$('#detailsName').textContent=username;$('#detailsUsername').textContent=`@${username}`;$('#activeAvatar').textContent=initials(username);$('#detailsAvatar').textContent=initials(username);updateActiveStatus();$('#messageInput').disabled=false;$('.send-btn').disabled=false;renderChats($('#searchInput').value);try{const data=await api(`/api/messages/${encodeURIComponent(username)}?limit=50`);state.messages.set(username,data.messages||[]);renderMessages();await markRead(username)}catch(error){toast(error.status===404?'این کاربر وجود ندارد.':error.message)}}
async function markRead(username){const data=await api(`/api/messages/${encodeURIComponent(username)}/read`,{method:'POST'});const chat=state.chats.find(c=>c.username===username);if(chat)chat.unreadCount=0;renderChats($('#searchInput').value);return data}
async function loadOlderMessages(){const username=state.activeUser;if(!username||state.loadingHistory.has(username))return;const list=state.messages.get(username)||[];if(!list.length)return;state.loadingHistory.add(username);try{const data=await api(`/api/messages/${encodeURIComponent(username)}?limit=50&before=${encodeURIComponent(list[0].id)}`);state.messages.set(username,[...(data.messages||[]),...list]);$('#loadOlder').hidden=!data.hasMore;renderMessages()}catch(e){toast(e.message)}finally{state.loadingHistory.delete(username)}}
function updateActiveStatus(){if(!state.activeUser){$('#activeStatus').textContent='—';return}if(state.typingUsers.has(state.activeUser))$('#activeStatus').textContent='در حال نوشتن…';else $('#activeStatus').textContent=state.onlineUsers.has(state.activeUser)?'آنلاین':'آفلاین'}
function scheduleReconnect(){if(state.intentionalClose||!localStorage.getItem(tokenKey)||state.reconnectTimer)return;const delay=Math.min(15000,1000*2**state.reconnectAttempt);state.reconnectAttempt++;setConnectionStatus(`تلاش مجدد تا ${Math.ceil(delay/1000)} ثانیه دیگر…`);state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;connectSocket()},delay)}
function connectSocket(){const token=localStorage.getItem(tokenKey);if(!token)return;if(state.socket&&(state.socket.readyState===WebSocket.OPEN||state.socket.readyState===WebSocket.CONNECTING))return;state.intentionalClose=false;setConnectionStatus('در حال اتصال…');let socket;try{socket=new WebSocket(wsUrl())}catch{scheduleReconnect();return}state.socket=socket;socket.onopen=()=>{state.reconnectAttempt=0;setConnectionStatus('اتصال لحظه‌ای فعال است');loadPresence()};socket.onmessage=event=>{try{const message=JSON.parse(event.data);if(message.type==='message')addMessage(message);if(message.type==='presence'){state.onlineUsers=new Set((message.users||[]).filter(Boolean));updateActiveStatus()}if(message.type==='typing'){const name=message.from||message.username;if(name){if(message.active)state.typingUsers.add(name);else state.typingUsers.delete(name);updateActiveStatus()}}if(message.type==='read')for(const id of message.ids||[])updateMessageStatus(id,{readAt:message.readAt,deliveredAt:message.readAt})}catch{}};socket.onerror=()=>setConnectionStatus('خطا در اتصال لحظه‌ای');socket.onclose=()=>{if(state.socket===socket)state.socket=null;if(!state.intentionalClose)scheduleReconnect();else setConnectionStatus('قطع شد')}}
function sendTyping(active){if(!state.socket||state.socket.readyState!==WebSocket.OPEN||!state.activeUser)return;state.socket.send(JSON.stringify({type:'typing',recipient:state.activeUser,active}))}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}state.intentionalClose=true;clearTimeout(state.reconnectTimer);state.reconnectTimer=null;if(state.socket)state.socket.close(1000,'logout');state.socket=null;localStorage.removeItem(tokenKey);state.user=null;state.activeUser=null;state.chats=[];state.users=[];state.messages.clear();state.onlineUsers.clear();state.typingUsers.clear();$('#profileBtn').textContent='؟';$('#activeName').textContent='یک گفتگو را انتخاب کنید';$('#activeStatus').textContent='—';$('#detailsName').textContent='گفتگویی انتخاب نشده';$('#detailsUsername').textContent='—';$('#messageInput').disabled=true;$('.send-btn').disabled=true;$('#messageArea').innerHTML='<div class="empty-conversation"><div class="empty-icon">✦</div><strong>به SEAM CHAT خوش آمدید</strong><span>برای شروع وارد حساب شوید.</span></div>';setConnectionStatus('متصل نیست');renderChats();showAuth('login')}
function showAuth(mode='login'){$('#authDialog').showModal();setAuthMode(mode)}
function closeDialog(id){const d=$(id);if(d.open)d.close()}
function setAuthMode(mode){$$('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));const register=mode==='register';$('#authTitle').textContent=register?'حساب جدید بسازید ✨':'خوش آمدید 👋';$('#authSubtitle').textContent=register?'چند ثانیه تا ساخت حساب SEAM CHAT فاصله دارید.':'برای ادامه وارد حساب SEAM CHAT شوید.';$('#authSubmit').textContent=register?'ساخت حساب':'ورود به SEAM CHAT';$('#authPassword').autocomplete=register?'new-password':'current-password';$('#authError').textContent='';$('#authForm').dataset.mode=mode}

$('#composer').addEventListener('submit',async e=>{e.preventDefault();const input=$('#messageInput');const body=input.value.trim();if(!body||!state.activeUser)return;const button=$('.send-btn');button.disabled=true;try{const clientMessageId=crypto.randomUUID();const data=await api('/api/messages',{method:'POST',body:JSON.stringify({recipient:state.activeUser,body,clientMessageId})});addMessage(data.message);input.value='';sendTyping(false);input.focus()}catch(error){if(error.status===401)await logout();else toast(error.message)}finally{if(state.activeUser)button.disabled=false}});
let typingStopTimer;$('#messageInput').addEventListener('input',()=>{sendTyping(true);clearTimeout(typingStopTimer);typingStopTimer=setTimeout(()=>sendTyping(false),1000)});$('#messageInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});
$('#searchInput').addEventListener('input',e=>searchUsers(e.target.value));$('#newChat').addEventListener('click',()=>showNewChat());$('#contactsBtn').addEventListener('click',()=>showNewChat());$('#chatsNav').addEventListener('click',()=>{});$('#chatSearch').addEventListener('click',()=>$('#searchInput').focus());$('#detailsSearch').addEventListener('click',()=>$('#searchInput').focus());$('#loadOlder').addEventListener('click',loadOlderMessages);$('#profileBtn').addEventListener('click',()=>state.user?logout():showAuth('login'));$('#detailsClose').addEventListener('click',()=>$('#detailsPanel').classList.remove('open'));$('#chatMore').addEventListener('click',()=>toast('گزینه‌های بیشتر در نسخه بعدی اضافه می‌شوند.'));$('#blockBtn').addEventListener('click',()=>toast('مسدودسازی هنوز به سیستم مدیریت حساب متصل نشده است.'));$('#attachBtn').addEventListener('click',()=>toast('ارسال فایل در حال آماده‌سازی فضای ذخیره‌سازی امن است.'));
$$('.auth-tab').forEach(tab=>tab.addEventListener('click',()=>setAuthMode(tab.dataset.mode)));$('#authClose').addEventListener('click',()=>{if(!state.user)toast('برای استفاده از SEAM CHAT باید وارد شوید.');else closeDialog('#authDialog')});$('#newChatClose').addEventListener('click',()=>closeDialog('#newChatDialog'));
function showNewChat(){if(!state.user)return showAuth('login');$('#newChatDialog').showModal();$('#targetUsername').focus()}
$('#newChatForm').addEventListener('submit',async e=>{e.preventDefault();const username=$('#targetUsername').value.trim();if(!username)return;try{const data=await api(`/api/users/search?q=${encodeURIComponent(username)}`);const exact=(data.users||[]).find(u=>u.username.toLowerCase()===username.toLowerCase());if(!exact)throw new Error('کاربری با این نام پیدا نشد.');closeDialog('#newChatDialog');$('#targetUsername').value='';await openChat(exact.username)}catch(error){toast(error.message)}});
$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const username=$('#authUsername').value.trim();const password=$('#authPassword').value;const mode=e.currentTarget.dataset.mode||'login';$('#authError').textContent='';$('#authSubmit').disabled=true;try{const endpoint=mode==='register'?'/api/auth/register':'/api/auth/login';const data=await api(endpoint,{method:'POST',body:JSON.stringify({username,password})});localStorage.setItem(tokenKey,data.token);closeDialog('#authDialog');await start();toast(mode==='register'?'حساب شما با موفقیت ساخته شد.':'خوش آمدید!')}catch(error){$('#authError').textContent=error.message}finally{$('#authSubmit').disabled=false}});
async function start(){await Promise.all([loadMe(),loadChats()]);await loadPresence();connectSocket();setConnectionStatus('در حال اتصال…')}
async function autoAuth(){if(!localStorage.getItem(tokenKey)){showAuth('login');return}try{await start()}catch(error){localStorage.removeItem(tokenKey);showAuth('login');$('#authError').textContent=error.message||'لطفاً دوباره وارد شوید.'}}
autoAuth();
