(() => {
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={user:null,activeUser:null,socket:null,reconnectTimer:null,reconnectAttempt:0,intentionalClose:false,chats:[],users:[],messages:new Map(),onlineUsers:new Set(),typingUsers:new Set(),hasMore:new Map(),loading:new Set(),searchTimer:null};
const TOKEN='seam_chat_token',API=(window.SEAM_API_BASE||location.origin).replace(/\/$/,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const initial=v=>(v||'?').slice(0,1).toUpperCase(), tm=v=>v?new Date(v).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'}):'', dt=v=>v?new Date(v).toLocaleDateString('fa-IR',{day:'numeric',month:'long'}):'';
const headers=()=>{const t=localStorage.getItem(TOKEN);return t?{Authorization:`Bearer ${t}`}:{}};
function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function status(t){const e=$('#connectionStatus');if(e)e.textContent=t}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,cache:'no-store',headers:{Accept:'application/json','Content-Type':'application/json',...headers(),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(d.error||`خطا (${r.status})`);e.status=r.status;throw e}return d}
function close(id){const d=$(id);if(d?.open)d.close()}
function setMode(mode){$$('.auth-tab').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));const reg=mode==='register';$('#authTitle').textContent=reg?'حساب جدید بسازید ✨':'خوش آمدید 👋';$('#authSubtitle').textContent=reg?'چند ثانیه تا ساخت حساب SEAM CHAT فاصله دارید.':'برای ادامه وارد حساب SEAM CHAT شوید.';$('#authSubmit').textContent=reg?'ساخت حساب':'ورود به SEAM CHAT';$('#authPassword').autocomplete=reg?'new-password':'current-password';$('#authForm').dataset.mode=mode;$('#authError').textContent=''}
function auth(mode='login'){const d=$('#authDialog');if(d&&!d.open)d.showModal();setMode(mode)}
function renderChats(filter=''){const q=filter.trim().toLowerCase(),list=$('#chatList');if(!list)return;const chats=state.chats.filter(c=>c.username.toLowerCase().includes(q)),users=state.users.filter(u=>u.username.toLowerCase().includes(q));const ch=chats.map(c=>`<button type="button" class="chat-row ${state.activeUser===c.username?'selected':''}" data-chat-user="${esc(c.username)}"><span class="avatar">${esc(initial(c.username))}</span><span class="chat-copy"><strong>${esc(c.username)}</strong><small>${esc(c.lastMessage||'گفتگو را شروع کنید')}</small></span><span class="chat-meta"><time>${tm(c.lastMessageAt)}</time>${c.unreadCount?`<b>${c.unreadCount}</b>`:''}</span></button>`).join('');const us=users.map(u=>`<button type="button" class="chat-row user-result" data-user="${esc(u.username)}"><span class="avatar avatar-green">${esc(initial(u.username))}</span><span class="chat-copy"><strong>${esc(u.username)}</strong><small>شروع گفتگوی جدید</small></span><span class="chat-meta"><small>کاربر</small></span></button>`).join('');if(q&&us)list.innerHTML=`<div class="result-title">کاربران</div>${us}${ch?`<div class="result-title">گفتگوها</div>${ch}`:''}`;else list.innerHTML=ch||(q?'<div class="empty-state">کاربری با این نام پیدا نشد.</div>':'<div class="empty-state">هنوز گفتگویی ندارید.<br>از «＋» برای شروع استفاده کنید.</div>')}
function renderMessages(keep=false){const area=$('#messageArea'),list=state.messages.get(state.activeUser)||[];if(!area)return;$('#loadOlder').hidden=!list.length||!state.hasMore.get(state.activeUser);if(!list.length){area.innerHTML='<div class="empty-conversation"><div class="empty-icon">✦</div><strong>هنوز پیامی نیست</strong><span>اولین پیام را شما بفرستید.</span></div>';return}const h=area.scrollHeight,t=area.scrollTop;let last='',html='';for(const m of list){const d=dt(m.createdAt);if(d!==last){html+=`<div class="date-pill">${esc(d)}</div>`;last=d}const mine=m.sender===state.user.username,s=m.readAt?'خوانده شد':m.deliveredAt?'تحویل شد':'ارسال شد';html+=`<article class="message ${mine?'sent':'received'}"><div>${mine?'':`<span class="bubble-avatar">${esc(initial(m.sender))}</span>`}<p>${esc(m.body)}</p><time>${tm(m.createdAt)}${mine?` · ${s}`:''}</time></div></article>`}area.innerHTML=html;area.scrollTop=keep?area.scrollHeight-h+t:area.scrollHeight}
function addMessage(m){if(!state.user||!m?.sender||!m?.recipient)return;const other=m.sender===state.user.username?m.recipient:m.sender,list=state.messages.get(other)||[],i=list.findIndex(x=>String(x.id)===String(m.id));if(i<0)list.push(m);else list[i]={...list[i],...m};list.sort((a,b)=>Number(a.id)-Number(b.id));state.messages.set(other,list);let c=state.chats.find(x=>x.username===other);if(!c){c={username:other,lastMessage:'',lastMessageAt:m.createdAt,unreadCount:0};state.chats.push(c)}c.lastMessage=m.body;c.lastMessageAt=m.createdAt;if(m.sender!==state.user.username&&state.activeUser!==other)c.unreadCount=(c.unreadCount||0)+1;state.chats.sort((a,b)=>new Date(b.lastMessageAt||0)-new Date(a.lastMessageAt||0));renderChats($('#searchInput').value);if(state.activeUser===other){renderMessages();if(m.sender!==state.user.username)markRead(other).catch(()=>{})}}
function patchMessage(id,p){for(const [u,l] of state.messages){const m=l.find(x=>String(x.id)===String(id));if(m){Object.assign(m,p);if(u===state.activeUser)renderMessages(true)}}}
async function loadMe(){const d=await api('/api/me');state.user=d.user;$('#profileBtn').textContent=initial(state.user.username)}
async function loadChats(){const d=await api('/api/chats');state.chats=d.chats||[];renderChats($('#searchInput').value)}
async function presence(){try{const d=await api('/api/presence');state.onlineUsers=new Set(d.users||[]);activeStatus()}catch{}}
function activeStatus(){if(!state.activeUser){$('#activeStatus').textContent='—';return}$('#activeStatus').textContent=state.typingUsers.has(state.activeUser)?'در حال نوشتن…':state.onlineUsers.has(state.activeUser)?'آنلاین':'آفلاین'}
async function search(q){clearTimeout(state.searchTimer);if(!q.trim()){state.users=[];renderChats('');return}state.searchTimer=setTimeout(async()=>{try{const d=await api(`/api/users/search?q=${encodeURIComponent(q.trim())}`);state.users=d.users||[]}catch{state.users=[]}renderChats(q)},180)}
async function openChat(name){if(!state.user)return auth();const q=String(name||'').trim();if(!q)return;if(q.toLowerCase()===state.user.username.toLowerCase())return toast('نمی‌توانید با خودتان گفتگو کنید.');try{const d=await api(`/api/users/search?username=${encodeURIComponent(q)}`),u=d.user||(d.users||[])[0];if(!u)throw new Error('کاربری با این نام پیدا نشد.');state.activeUser=u.username;state.messages.set(u.username,[]);state.hasMore.set(u.username,false);$('#activeName').textContent=u.username;$('#detailsName').textContent=u.username;$('#detailsUsername').textContent='@'+u.username;$('#activeAvatar').textContent=initial(u.username);$('#detailsAvatar').textContent=initial(u.username);$('#messageInput').disabled=false;$('.send-btn').disabled=false;activeStatus();renderChats($('#searchInput').value);document.body.dataset.mobileView='chat';const h=await api(`/api/messages/${encodeURIComponent(u.username)}?limit=50`);state.messages.set(u.username,h.messages||[]);state.hasMore.set(u.username,!!h.hasMore);renderMessages();await markRead(u.username)}catch(e){if(e.status===401){localStorage.removeItem(TOKEN);toast('نشست شما منقضی شده است. دوباره وارد شوید.');return auth()}toast(e.message)}}
async function markRead(u){const d=await api(`/api/messages/${encodeURIComponent(u)}/read`,{method:'POST'});const c=state.chats.find(x=>x.username===u);if(c)c.unreadCount=0;renderChats($('#searchInput').value);return d}
async function older(){const u=state.activeUser;if(!u||state.loading.has(u))return;const l=state.messages.get(u)||[];if(!l.length||!state.hasMore.get(u))return;state.loading.add(u);try{const d=await api(`/api/messages/${encodeURIComponent(u)}?limit=50&before=${encodeURIComponent(l[0].id)}`);state.messages.set(u,[...(d.messages||[]),...l]);state.hasMore.set(u,!!d.hasMore);renderMessages(true)}catch(e){toast(e.message)}finally{state.loading.delete(u)}}
function wsUrl(){const u=new URL(API+'/ws');u.protocol=u.protocol==='https:'?'wss:':'ws:';u.searchParams.set('token',localStorage.getItem(TOKEN)||'');return u.toString()}
function reconnect(){if(state.intentionalClose||!localStorage.getItem(TOKEN)||state.reconnectTimer)return;const d=Math.min(15000,1000*2**state.reconnectAttempt++);status(`تلاش مجدد تا ${Math.ceil(d/1000)} ثانیه دیگر…`);state.reconnectTimer=setTimeout(()=>{state.reconnectTimer=null;socket()},d)}
function socket(){if(!localStorage.getItem(TOKEN)||state.socket?.readyState===WebSocket.OPEN||state.socket?.readyState===WebSocket.CONNECTING)return;state.intentionalClose=false;status('در حال اتصال…');let ws;try{ws=new WebSocket(wsUrl())}catch{return reconnect()}state.socket=ws;ws.onopen=()=>{state.reconnectAttempt=0;status('اتصال لحظه‌ای فعال است');presence()};ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='message')addMessage(m);else if(m.type==='presence'){state.onlineUsers=new Set(m.users||[]);activeStatus()}else if(m.type==='typing'){const n=m.from||m.username;if(n){m.active?state.typingUsers.add(n):state.typingUsers.delete(n);activeStatus()}}else if(m.type==='read')for(const id of m.ids||[])patchMessage(id,{readAt:m.readAt,deliveredAt:m.readAt})}catch{}};ws.onerror=()=>status('خطا در اتصال لحظه‌ای');ws.onclose=()=>{if(state.socket===ws)state.socket=null;if(!state.intentionalClose)reconnect()}}
function typing(active){if(state.socket?.readyState===WebSocket.OPEN&&state.activeUser)state.socket.send(JSON.stringify({type:'typing',recipient:state.activeUser,active}))}
async function logout(){try{await api('/api/auth/logout',{method:'POST'})}catch{}state.intentionalClose=true;clearTimeout(state.reconnectTimer);state.socket?.close(1000,'logout');localStorage.removeItem(TOKEN);state.socket=null;state.user=null;state.activeUser=null;state.chats=[];state.users=[];state.messages.clear();state.onlineUsers.clear();$('#profileBtn').textContent='؟';$('#messageInput').disabled=true;$('.send-btn').disabled=true;$('#activeName').textContent='یک گفتگو را انتخاب کنید';$('#activeStatus').textContent='—';$('#messageArea').innerHTML='<div class="empty-conversation"><div class="empty-icon">✦</div><strong>به SEAM CHAT خوش آمدید</strong><span>برای شروع وارد حساب شوید.</span></div>';status('متصل نیست');renderChats();auth()}
let typeTimer;
$('#composer')?.addEventListener('submit',async e=>{e.preventDefault();const i=$('#messageInput'),body=i.value.trim();if(!body||!state.activeUser)return;const b=$('.send-btn');b.disabled=true;try{const d=await api('/api/messages',{method:'POST',body:JSON.stringify({recipient:state.activeUser,body,clientMessageId:crypto.randomUUID()})});addMessage(d.message);i.value='';typing(false);i.focus()}catch(e){if(e.status===401)logout();else toast(e.message)}finally{b.disabled=!state.activeUser}});
$('#messageInput')?.addEventListener('input',()=>{typing(true);clearTimeout(typeTimer);typeTimer=setTimeout(()=>typing(false),1000)});$('#messageInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('#composer').requestSubmit()}});$('#searchInput')?.addEventListener('input',e=>search(e.target.value));$('#newChat')?.addEventListener('click',()=>newChat());$('#contactsBtn')?.addEventListener('click',()=>newChat());$('#chatSearch')?.addEventListener('click',()=>$('#searchInput')?.focus());$('#detailsSearch')?.addEventListener('click',()=>$('#searchInput')?.focus());$('#loadOlder')?.addEventListener('click',older);$('#profileBtn')?.addEventListener('click',()=>state.user?logout():auth());$('#detailsClose')?.addEventListener('click',()=>$('#detailsPanel')?.classList.remove('open'));$('#authClose')?.addEventListener('click',()=>state.user?close('#authDialog'):toast('برای استفاده باید وارد شوید.'));$('#newChatClose')?.addEventListener('click',()=>close('#newChatDialog'));$$('.auth-tab').forEach(x=>x.addEventListener('click',()=>setMode(x.dataset.mode)));
function newChat(){if(!state.user)return auth();const d=$('#newChatDialog');if(!d.open)d.showModal();$('#targetUsername').focus()}
$('#newChatForm')?.addEventListener('submit',async e=>{e.preventDefault();const u=$('#targetUsername').value.trim();if(!u)return;const old=state.activeUser;await openChat(u);if(state.activeUser&&state.activeUser!==old){close('#newChatDialog');$('#targetUsername').value=''}});
$('#authForm')?.addEventListener('submit',async e=>{e.preventDefault();const username=$('#authUsername').value.trim(),password=$('#authPassword').value,mode=e.currentTarget.dataset.mode||'login';$('#authError').textContent='';$('#authSubmit').disabled=true;try{const d=await api(mode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});localStorage.setItem(TOKEN,d.token);state.user=d.user;close('#authDialog');$('#authUsername').value='';$('#authPassword').value='';$('#profileBtn').textContent=initial(state.user.username);await loadChats();await presence();socket();toast(mode==='register'?'حساب ساخته شد؛ خوش آمدید!':'خوش آمدید!')}catch(e){$('#authError').textContent=e.message}finally{$('#authSubmit').disabled=false}});
document.addEventListener('click',e=>{const row=e.target.closest('[data-chat-user],[data-user]');if(row){e.preventDefault();openChat(row.dataset.chatUser||row.dataset.user)}});
async function boot(){renderChats();if(!localStorage.getItem(TOKEN))return auth();try{await loadMe();await loadChats();await presence();socket()}catch{localStorage.removeItem(TOKEN);auth()}}
window.addEventListener('online',()=>state.user&&socket());window.addEventListener('offline',()=>status('اینترنت قطع است'));boot();
})();
