-- Replace these codes before production use.
INSERT INTO invite_codes(code, created_at) VALUES
('SEAM-01', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-02', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-03', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-04', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-05', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000)
ON CONFLICT (code) DO NOTHING;
