name = "seam-chat-api"
main = "src/index.js"
compatibility_date = "2026-09-08"
compatibility_flags = ["nodejs_compat"]

[vars]
SESSION_DAYS = "30"

[[d1_databases]]
binding = "DB"
database_name = "my-seam-account"
database_id = "0015651c-a248-45a5-b485-688413a7b27c"
migrations_dir = "migrations"

[durable_objects]
bindings = [
  { name = "PRESENCE", class_name = "Presence" }
]

[[migrations]]
tag = "v1"
new_classes = ["Presence"]

[observability]
enabled = true
