-- Initial SEAM Chat beta invite codes.
-- Each code is single-use; Database.kt seeds them with ON CONFLICT DO NOTHING.
INSERT INTO invite_codes(code, created_at) VALUES
('SEAM-7K4P-9X2M', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-3Q8N-5R7T', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-6V2L-8C9H', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-4D7W-2P6Y', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-9M3F-7J5K', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-2H8R-4N6V', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-5T9B-3X7Q', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-8P4C-6L2D', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-1Y7G-9W3S', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000),
('SEAM-6N5Z-2K8M', EXTRACT(EPOCH FROM NOW())::BIGINT * 1000)
ON CONFLICT (code) DO NOTHING;
